<a href="https://colab.research.google.com/github/YashPatel1508/NumPy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,1,2,3,4,5])
b = a.shape
print(b)

(6,)


In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7)])
b = a.shape
print(b)

(2, 6)


In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7)], dtype= float)
print(a)

[[ 1.  1.  2.  3.  4.  5.]
 [ 1.  3.  5.  4. 67.  7.]]


In [ ]:
# create the numpy of zeros
x = np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create the numpy of perticular values
x = np.full((5,7),2)
print(x)

[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]


In [ ]:
# create an identity matrix
x = np.eye(4) # this is create the array and dignar values are 1 and remaining are 0
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# random integer value
x = np.random.randint(1,100,(3,4))
print(x)

[[67 38 38 96]
 [32 80 49  9]
 [83 14 54 60]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
x = np.linspace(10,30,6)
print(x)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
x = np.arange(10,50,7)
print(x)

[10 17 24 31 38 45]


In [ ]:
#  convert the list to the np array
x = [1,2,3,4,5,6,7,8,9]
y = np.asarray(x)
print(y)
print(type(y))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7)])
a.ndim

2

In [ ]:
a = [[2 ,2 ,2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2]]

b = np.array(a)
b.flatten() # this is convert to the one dimention


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
a = [[2 ,2 ,2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2]]
b = np.array(a)
print(b.size) # count the element


35


In [ ]:
a = [[2 ,2 ,2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2]]
b = np.array(a)
print(b.reshape(7,5)) # Reshape

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.sum(a, axis=0) # Column-wise sum

array([ 3,  6, 15, 11, 77, 19])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.sum(a, axis=1) # Row-wise sum

array([16, 87, 28])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.sort(a) #Sort Array

array([[ 1,  1,  2,  3,  4,  5],
       [ 1,  3,  4,  5,  7, 67],
       [ 1,  2,  4,  6,  7,  8]])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.unique(a) #unique Array

array([ 1,  2,  3,  4,  5,  6,  7,  8, 67])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
a[a < 50] = 0 # replace value
print(a)


[[ 0  0  0  0  0  0]
 [ 0  0  0  0 67  0]
 [ 0  0  0  0  0  0]]


In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10,3,64,5), (1,33,25,42,67,7)])

np.vstack((a,b)) # vertical stack array


array([[ 1,  1,  2,  3,  4,  5],
       [ 1,  3,  5,  4, 67,  7],
       [ 1,  2,  8,  4,  6,  7],
       [ 1, 34, 10,  3, 64,  5],
       [ 1, 33, 25, 42, 67,  7]])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10,3,64,5), (1,33,25,42,67,7), (11,23,38,4,65,7)])

np.hstack((a,b)) # horizontal stack array

array([[ 1,  1,  2,  3,  4,  5,  1, 34, 10,  3, 64,  5],
       [ 1,  3,  5,  4, 67,  7,  1, 33, 25, 42, 67,  7],
       [ 1,  2,  8,  4,  6,  7, 11, 23, 38,  4, 65,  7]])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10),(3,64,5), (1,33,25),(42,67,7), (11,23,38),(4,65,7)])

np.dot(a,b) #dot array \(C_{i,j}=\sum _{k=0}^{n-1}a_{i,k}\cdot b_{k,j}\)

array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])

In [ ]:
np.random.rand(5) # random number generate


array([0.98214826, 0.02671128, 0.18237308, 0.27210599, 0.32292791])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
a.T  # Transpose

array([[ 1,  1,  1],
       [ 1,  3,  2],
       [ 2,  5,  8],
       [ 3,  4,  4],
       [ 4, 67,  6],
       [ 5,  7,  7]])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.std(a) # Standard deviation

np.float64(14.646977524980501)

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.var(a) # Variance

np.float64(214.53395061728395)

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
a_3d = a.reshape(2,2, 3, 2)

print(a_3d.ndim)
print(a_3d)
print(a_3d.flatten()) # flatten list
np.argmax(a) # index of max

4
[[[[ 1  1]
   [ 2  3]
   [ 4  5]]

  [[ 1  3]
   [ 5  4]
   [67  7]]]


 [[[ 1  2]
   [ 8  4]
   [ 6  7]]

  [[ 1  2]
   [ 8  4]
   [ 6  7]]]]
[ 1  1  2  3  4  5  1  3  5  4 67  7  1  2  8  4  6  7  1  2  8  4  6  7]


np.int64(10)

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
np.argmin(a) # index of min

np.int64(0)

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
np.clip(a,5,100) # it is doing like the conver the all lower number to this perticular number


array([[ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5, 67,  7],
       [ 5,  5,  8,  5,  6,  7],
       [ 5,  5,  8,  5,  6,  7]])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
np.where(a > 7, 1, 0) # where condition

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
b =(a - a.min()) / (a.max() - a.min())
print(b) # normalization

[[0.         0.         0.01515152 0.03030303 0.04545455 0.06060606]
 [0.         0.03030303 0.06060606 0.04545455 1.         0.09090909]
 [0.         0.01515152 0.10606061 0.04545455 0.07575758 0.09090909]
 [0.         0.01515152 0.10606061 0.04545455 0.07575758 0.09090909]]


In [ ]:
a = np.array([(1,1,2)])
a + np.array([3,2,1]) #Broadcasting

array([[4, 3, 3]])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10),(3,64,5), (1,33,25),(42,67,7), (11,23,38),(4,65,7)])
np.matmul(a,b) # same as dot function (multiplication)


array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])

In [ ]:
a = np.array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])
np.linalg.eig(a) #Eigen values


EigResult(eigenvalues=array([3967.73671301,   33.27538674, -625.01209975]), eigenvectors=array([[-0.21434062, -0.96924162,  0.41300514],
       [-0.90913762,  0.12838535, -0.65464231],
       [-0.35710906,  0.20997116,  0.63314311]]))

In [ ]:
a = np.array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])
np.linalg.inv(a) #Inverse matrix

array([[ 0.02635725,  0.0007174 , -0.017495  ],
       [-0.00327707, -0.00033058,  0.00345016],
       [-0.00587308,  0.00043188,  0.00267764]])

In [ ]:
a = np.array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])
np.linalg.det(a) #Determinate

np.float64(-82519081.00000006)

In [ ]:
a = np.array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])
np.percentile(a,87.5) #Percentile

np.float64(2655.0)

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10,3,64,5), (1,33,25,42,67,7), (11,23,38,4,65,7)])
np.corrcoef(a,b) #Correlation

array([[1.        , 0.46051453, 0.66955589, 0.16217309, 0.23510743,
        0.11698707],
       [0.46051453, 1.        , 0.2985275 , 0.86838604, 0.76880568,
        0.84355184],
       [0.66955589, 0.2985275 , 1.        , 0.09728206, 0.20483487,
        0.38224333],
       [0.16217309, 0.86838604, 0.09728206, 1.        , 0.80113065,
        0.85602093],
       [0.23510743, 0.76880568, 0.20483487, 0.80113065, 1.        ,
        0.70006163],
       [0.11698707, 0.84355184, 0.38224333, 0.85602093, 0.70006163,
        1.        ]])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10,3,64,5), (1,33,25,42,67,7), (11,23,38,4,65,7)])
np.cov(a,b) #Covariance

array([[  2.66666667,  19.4       ,   3.06666667,   6.6       ,
          9.26666667,   4.46666667],
       [ 19.4       , 665.5       ,  21.6       , 558.3       ,
        478.7       , 508.8       ],
       [  3.06666667,  21.6       ,   7.86666667,   6.8       ,
         13.86666667,  25.06666667],
       [  6.6       , 558.3       ,   6.8       , 621.1       ,
        481.9       , 498.8       ],
       [  9.26666667, 478.7       ,  13.86666667, 481.9       ,
        582.56666667, 395.06666667],
       [  4.46666667, 508.8       ,  25.06666667, 498.8       ,
        395.06666667, 546.66666667]])

In [ ]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.save("data.npy", a) # save Array

In [ ]:
np.load("data.npy") # Load File

array([[ 1,  1,  2,  3,  4,  5],
       [ 1,  3,  5,  4, 67,  7],
       [ 1,  2,  8,  4,  6,  7]])